spring:
  application:
    name: libraryapi
  datasource:
    url: jdbc:postgresql://localhost:5433/gow
    username: postgres
    password: senha
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none